# Generated by Django 5.0.2 on 2024-02-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=300)),
                ('content1', models.TextField(max_length=300)),
                ('content2', models.TextField(max_length=300)),
                ('content3', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
