# Generated by Django 5.0.2 on 2024-02-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0004_obuna_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obuna',
            name='price',
            field=models.CharField(max_length=5),
        ),
    ]
