# Generated by Django 5.0.2 on 2024-02-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0007_category_alter_izoh_options_alter_obuna_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
