# Generated by Django 5.0.2 on 2024-02-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0008_alter_book_data_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
    ]
