# Generated by Django 5.0.2 on 2024-02-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0009_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='literal',
            field=models.ManyToManyField(blank=True, related_name='literal', to='my_book.country'),
        ),
    ]
