# Generated by Django 5.0.2 on 2024-02-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0010_book_literal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cat_photos/%Y/%m/%d', verbose_name='Category_photo'),
        ),
    ]
