# Generated by Django 5.0.2 on 2024-02-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0011_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
