# Generated by Django 5.0.2 on 2024-02-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0012_alter_book_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Davlator', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.AddField(
            model_name='country',
            name='content',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='country_photos/%Y/%m/%d', verbose_name='Country_photo'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
